# Example Apache integration using mod_lua access checker.

LoadModule lua_module modules/mod_lua.so

<VirtualHost *:8082>
    ServerName localhost
    DocumentRoot "/var/www/html"

    LuaHookAccessChecker "/path/to/apache-botwall.lua" botwall_access_checker early

    ProxyPass / http://127.0.0.1:4000/
    ProxyPassReverse / http://127.0.0.1:4000/
</VirtualHost>
