[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:botwall]
command=python -m botwall
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/botwall.err.log
stdout_logfile=/var/log/botwall.out.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx-error.log
stdout_logfile=/var/log/nginx-access.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
