-- Apache mod_lua access checker — auto-generated by scripts/render_deploy.py
-- Source: botwall.toml  |  Botwall API: http://127.0.0.1:4000
local http = require("socket.http")

BOTWALL_CHECK_URL  = "http://127.0.0.1:4000/bw/check"
BOTWALL_CHALLENGE  = "http://127.0.0.1:4000/bw/challenge"
BOTWALL_DECOY      = "http://127.0.0.1:4000/bw/decoy/0"

function botwall_access_checker(r)
    local req = {
        url    = BOTWALL_CHECK_URL,
        method = "GET",
        headers = {
            ["X-Original-URI"]   = r.unparsed_uri or r.uri,
            ["X-Forwarded-For"]  = r.useragent_ip or "0.0.0.0",
            ["User-Agent"]       = r.headers_in["User-Agent"] or "",
            ["Accept-Language"]  = r.headers_in["Accept-Language"] or "",
            ["Cookie"]           = r.headers_in["Cookie"] or "",
        },
    }

    local _, code, headers = http.request(req)
    if not code or code >= 500 then
        return apache2.DECLINED
    end

    local decision = headers["x-botwall-decision"] or "allow"
    if decision == "challenge" then
        r.headers_out["Location"] = BOTWALL_CHALLENGE .. "?path=" .. r:escape_uri(r.uri)
        return 302
    end
    if decision == "decoy" then
        r.headers_out["Location"] = BOTWALL_DECOY
        return 302
    end
    return apache2.DECLINED
end
