#!/usr/bin/env python3
"""
scripts/render_deploy.py

Renders deploy/ config templates using the active botwall.toml settings.
Outputs ready-to-use Nginx, Caddy, and Apache configs to deploy/rendered/.

Usage:
    python scripts/render_deploy.py
    python scripts/render_deploy.py --config /path/to/custom.toml
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from botwall.config import load_settings


NGINX_TEMPLATE = """\
# Nginx integration — auto-generated by scripts/render_deploy.py
# Source: botwall.toml  |  Botwall API: {api_url}
upstream botwall_api {{
    server {api_host}:{api_port};
}}

server {{
    listen 8080;
    server_name _;

    location = /__bw_check {{
        internal;
        proxy_pass http://botwall_api/bw/check;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Language $http_accept_language;
        proxy_set_header Cookie $http_cookie;
    }}

    location / {{
        auth_request /__bw_check;
        auth_request_set $bw_decision $upstream_http_x_botwall_decision;

        if ($bw_decision = challenge) {{
            return 302 {api_url}/bw/challenge?path=$uri;
        }}
        if ($bw_decision = decoy) {{
            return 302 {api_url}/bw/decoy/0;
        }}

        proxy_pass http://botwall_api;
        proxy_set_header X-Forwarded-For $remote_addr;
    }}
}}
"""

CADDYFILE_TEMPLATE = """\
# Caddy integration — auto-generated by scripts/render_deploy.py
# Source: botwall.toml  |  Botwall API: {api_url}
:8081 {{
    forward_auth {api_host}:{api_port} {{
        uri /bw/check
        copy_headers X-Botwall-Decision X-Botwall-Score X-Botwall-Reasons
    }}

    @challenge header X-Botwall-Decision challenge
    redir @challenge {api_url}/bw/challenge?path={{uri}}

    @decoy header X-Botwall-Decision decoy
    redir @decoy {api_url}/bw/decoy/0

    reverse_proxy {api_host}:{api_port}
}}
"""

APACHE_CONF_TEMPLATE = """\
# Apache integration — auto-generated by scripts/render_deploy.py
# Source: botwall.toml  |  Botwall API: {api_url}
LoadModule lua_module modules/mod_lua.so

<VirtualHost *:8082>
    ServerName localhost
    DocumentRoot "/var/www/html"

    LuaHookAccessChecker "/path/to/deploy/apache-botwall.lua" botwall_access_checker early

    ProxyPass / {api_url}/
    ProxyPassReverse / {api_url}/
</VirtualHost>
"""

APACHE_LUA_TEMPLATE = """\
-- Apache mod_lua access checker — auto-generated by scripts/render_deploy.py
-- Source: botwall.toml  |  Botwall API: {api_url}
local http = require("socket.http")

BOTWALL_CHECK_URL  = "{api_url}/bw/check"
BOTWALL_CHALLENGE  = "{api_url}/bw/challenge"
BOTWALL_DECOY      = "{api_url}/bw/decoy/0"

function botwall_access_checker(r)
    local req = {{
        url    = BOTWALL_CHECK_URL,
        method = "GET",
        headers = {{
            ["X-Original-URI"]   = r.unparsed_uri or r.uri,
            ["X-Forwarded-For"]  = r.useragent_ip or "0.0.0.0",
            ["User-Agent"]       = r.headers_in["User-Agent"] or "",
            ["Accept-Language"]  = r.headers_in["Accept-Language"] or "",
            ["Cookie"]           = r.headers_in["Cookie"] or "",
        }},
    }}

    local _, code, headers = http.request(req)
    if not code or code >= 500 then
        return apache2.DECLINED
    end

    local decision = headers["x-botwall-decision"] or "allow"
    if decision == "challenge" then
        r.headers_out["Location"] = BOTWALL_CHALLENGE .. "?path=" .. r:escape_uri(r.uri)
        return 302
    end
    if decision == "decoy" then
        r.headers_out["Location"] = BOTWALL_DECOY
        return 302
    end
    return apache2.DECLINED
end
"""


def render(cfg) -> None:
    out = Path("deploy") / "rendered"
    out.mkdir(parents=True, exist_ok=True)

    api_url = cfg.botwall_api_url()
    ctx = {"api_url": api_url, "api_host": cfg.app_host, "api_port": cfg.app_port}

    (out / "nginx.conf").write_text(NGINX_TEMPLATE.format(**ctx))
    (out / "Caddyfile").write_text(CADDYFILE_TEMPLATE.format(**ctx))
    (out / "apache.conf").write_text(APACHE_CONF_TEMPLATE.format(**ctx))
    (out / "apache-botwall.lua").write_text(APACHE_LUA_TEMPLATE.format(**ctx))

    print(f"Rendered configs to {out}/")
    for f in sorted(out.iterdir()):
        print(f"  {f.name}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Render deploy configs from botwall.toml")
    parser.add_argument("--config", help="Path to a custom TOML config file")
    args = parser.parse_args()

    if args.config:
        import os
        os.environ["BOTWALL_CONFIG"] = args.config

    cfg = load_settings()
    render(cfg)


if __name__ == "__main__":
    main()
